"""add_mcp_tokens_table

Revision ID: 7cd589ffac5e
Revises: a6609de40827
Create Date: 2026-07-08 09:52:33.073063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd589ffac5e'
down_revision: Union[str, Sequence[str], None] = 'a6609de40827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'mcp_tokens',
        sa.Column('id', sa.String(32), primary_key=True),
        sa.Column('user_id', sa.String(32), nullable=False, index=True),
        sa.Column('name', sa.String(200), nullable=False),
        sa.Column('token_prefix', sa.String(32), nullable=False),
        sa.Column('token_hash', sa.String(64), unique=True, index=True, nullable=False),
        sa.Column('scopes', sa.JSON, nullable=False),
        sa.Column('constraints', sa.JSON, nullable=True),
        sa.Column('created_at', sa.DateTime, nullable=False),
        sa.Column('last_used_at', sa.DateTime, nullable=True),
        sa.Column('expires_at', sa.DateTime, nullable=True),
        sa.Column('revoked_at', sa.DateTime, nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mcp_tokens')
    # ### end Alembic commands ###
