"""add_orientation_column_to_nodes

Revision ID: c112271853fd
Revises: 7cd589ffac5e
Create Date: 2026-07-08 20:35:28.982117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c112271853fd'
down_revision: Union[str, Sequence[str], None] = '7cd589ffac5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('orientation', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'orientation')
    # ### end Alembic commands ###
