"""initial_schema

Revision ID: e10b08b208d0
Revises: 
Create Date: 2026-07-06 20:02:46.589856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e10b08b208d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studios',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('studio_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folders_studio_id'), 'folders', ['studio_id'], unique=False)
    op.create_table('boards',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('studio_id', sa.String(length=32), nullable=False),
    sa.Column('folder_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boards_folder_id'), 'boards', ['folder_id'], unique=False)
    op.create_index(op.f('ix_boards_studio_id'), 'boards', ['studio_id'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('board_id', sa.String(length=32), nullable=False),
    sa.Column('from_node', sa.String(length=64), nullable=False),
    sa.Column('from_port', sa.String(length=64), nullable=False),
    sa.Column('to_node', sa.String(length=64), nullable=False),
    sa.Column('to_port', sa.String(length=64), nullable=False),
    sa.Column('curved', sa.Boolean(), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edges_board_id'), 'edges', ['board_id'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('board_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('w', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('ports', sa.JSON(), nullable=False),
    sa.Column('blocks', sa.JSON(), nullable=False),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_board_id'), 'nodes', ['board_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nodes_board_id'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_edges_board_id'), table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_boards_studio_id'), table_name='boards')
    op.drop_index(op.f('ix_boards_folder_id'), table_name='boards')
    op.drop_table('boards')
    op.drop_index(op.f('ix_folders_studio_id'), table_name='folders')
    op.drop_table('folders')
    op.drop_table('studios')
    # ### end Alembic commands ###
